# Generated by Django 4.2.7 on 2024-01-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('locker_room', models.BooleanField(default=False)),
                ('shower_room', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reward_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kind_of_sport', models.CharField(max_length=100)),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.ManyToManyField(related_name='trainers', to='sporting.place', verbose_name='Тренеры в зале')),
                ('rewards', models.ManyToManyField(blank=True, null=True, related_name='awarded', to='sporting.reward', verbose_name='Награжденные')),
            ],
        ),
    ]
