# Generated by Django 4.2.7 on 2024-01-01 09:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='RU')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sporting.jurisdiction'),
        ),
    ]
