# Generated by Django 4.2.7 on 2024-01-01 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0002_jurisdiction_place_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
