# Generated by Django 5.0.1 on 2024-04-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0003_place__index_place_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='place',
        ),
        migrations.AddField(
            model_name='trainer',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='sporting.place', verbose_name='Место преподавания'),
        ),
    ]
