# Generated by Django 4.2.7 on 2024-01-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0003_jurisdiction_latitude_jurisdiction_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='rewards',
            field=models.ManyToManyField(related_name='awarded', to='sporting.reward', verbose_name='Награжденные'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='kind_of_sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sporting.sport'),
        ),
    ]
