# Generated by Django 4.2.7 on 2024-01-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0005_remove_place_location_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='director',
        ),
        migrations.AddField(
            model_name='place',
            name='administrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название спорта'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_type',
            field=models.CharField(max_length=100, verbose_name='Тип спорта'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='place',
            field=models.ManyToManyField(related_name='trainers', to='sporting.place', verbose_name='Место обучения'),
        ),
    ]
