# Generated by Django 4.2.7 on 2024-01-01 12:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0006_remove_place_director_place_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='administrator',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='RU'),
        ),
        migrations.AlterField(
            model_name='place',
            name='jurisdiction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Jurisdiction',
        ),
    ]
