# Generated by Django 4.2.7 on 2024-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0007_remove_place_administrator_place_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='locker_room',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='shower_room',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
