# Generated by Django 4.2.7 on 2024-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0008_alter_place_locker_room_alter_place_shower_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
