# Generated by Django 4.2.7 on 2024-01-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0009_alter_place_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Учредитель'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='place',
            field=models.ManyToManyField(related_name='trainers', to='sporting.place', verbose_name='Место преподавания'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='rewards',
            field=models.ManyToManyField(related_name='awarded', to='sporting.reward', verbose_name='Награды'),
        ),
    ]
