# Generated by Django 4.2.7 on 2024-01-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0010_trainer_is_published_alter_place_jurisdiction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='age',
        ),
        migrations.AddField(
            model_name='trainer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
