# Generated by Django 4.2.7 on 2024-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0011_remove_trainer_age_trainer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.DateField(blank=True, null=True),
        ),
    ]
