# Generated by Django 4.2.7 on 2024-01-01 13:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0012_alter_trainer_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportFederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название федерации')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес федерации')),
                ('president', models.CharField(max_length=100, verbose_name='Президент федерации')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='RU')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email федерации')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='federation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport', to='sporting.sportfederation'),
        ),
    ]
