# Generated by Django 4.2.7 on 2024-01-01 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0013_sportfederation_sport_federation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfederation',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='sportfederation',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
