# Generated by Django 4.2.7 on 2024-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0015_sportfederation_phone_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='rewards',
            field=models.ManyToManyField(blank=True, null=True, related_name='awarded', to='sporting.reward', verbose_name='Награды'),
        ),
    ]
