# Generated by Django 4.2.7 on 2024-01-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0016_alter_trainer_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название секции')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='sporting.sportfederation')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='sporting.place')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='kind_of_sport',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='section',
            name='trainers',
            field=models.ManyToManyField(related_name='sections', to='sporting.trainer', verbose_name='Тренеры'),
        ),
    ]
