# Generated by Django 4.2.7 on 2024-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0018_trainer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='type_of_sport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид спорта'),
        ),
    ]
