# Generated by Django 4.2.7 on 2024-01-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0019_trainer_type_of_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид спорта')),
                ('type_of_sport', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип спорта')),
                ('federation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport', to='sporting.sportfederation')),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='sporting.sport', verbose_name='Спорт'),
        ),
    ]
