# Generated by Django 4.2.7 on 2024-01-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0020_sport_trainer_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='type_of_sport',
        ),
    ]
