# Generated by Django 4.2.7 on 2024-01-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0021_remove_trainer_type_of_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='is_olimpic',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Олимпиада'),
        ),
    ]
