# Generated by Django 4.2.7 on 2024-01-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0023_sport_is_for_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='sporting.sport'),
        ),
    ]
