# Generated by Django 4.2.7 on 2024-01-06 10:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0024_section_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[110, 110], upload_to='trainers/djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='place',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainers', to='sporting.place', verbose_name='Место преподавания'),
        ),
    ]
