# Generated by Django 4.2.7 on 2024-01-06 10:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sporting', '0025_alter_trainer_photo_alter_trainer_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=False, null=True, quality=100, scale=None, size=[120, 110], upload_to='trainers/djangodbmodelsfieldscharfield'),
        ),
    ]
